#
# Makefile - simple makefile for spin button stuff.
# set up for Solaris 2.6, CDE 1.3, but can easily be adapted
# to different platforms (one reason why I kept it simple).
#
# Jerry Adair
# adair@iglou.com
#

#
# Set the basic stuff.
#
CC = gcc -Wall
#CC= gcc  -Wimplicit-function-declaration -Wunused -Wswitch -Wcomment \
         -Wtrigraphs -Wformat -Wchar-subscripts -Wparentheses 

MOTIF_INCLUDE=-I/opt/motif12/include
#MOTIF_INCLUDE=-I/opt/lesstif/include
#MOTIF_INCLUDE=-I/usr/include
#MOTIF_INCLUDE=-I/usr/dt/include

MOTIF_LIB=-L/opt/motif12/lib -lXm
#MOTIF_LIB=-L/opt/lesstif/lib -lXm
#MOTIF_LIB=-L/usr/lib -lXm
#MOTIF_LIB=-L/usr/dt/lib -lXm

X_INCLUDE=-I/usr/X11R6/include
#X_INCLUDE=-I/usr/include
#X_INCLUDE=-I/usr/openwin/include

X_LIB=-L/usr/X11R6/lib -lXt -lX11
#X_LIB=-L/usr/lib -lXt -lX11 
#X_LIB=-L/usr/openwin/lib -lXt -lX11 

CFLAGS = -g -I.. -I. -DFUNCPROTOC $(MOTIF_INCLUDE) $(X_INCLUDE)

OBJECTS = ComboBox.o

LIBS = $(MOTIF_LIB) $(X_LIB)

#
# Now set what you can do with this makefile.
#
all:		SpinButton.o

demo:		SpinButton.o demo.o
		$(CC) $(CFLAGS) -o demo demo.o SpinButton.o $(LIBS) 

SpinButton.o:	SpinButton.c SpinButton.h SpinButtonP.h
		$(CC) $(CFLAGS) -c SpinButton.c

clean:		
		@echo "Cleaning..."
		@-rm -f *.o demo *~
		@echo "Done."
