...\" Copyright (c) 1998   Alexander Yukhimets. All rights reserved.
.TH AxY FTP 1X "22 January 2000"
.SH NAME
\fBaxyftp\fP \- GUI ftp client for the X Window System
.SH SYNTAX
.B axyftp
[ 
.RI 
.RI X 
.RI toolkit 
.RI options
|
.RI GTK
.RI options
]
.SH DESCRIPTION
The
.I axyftp
program is not-yet-very-sophisticated ftp client with intuitive graphical user
interface. 
.LP
Documentation for the program is available in html format as on-line help.
To use on-line help you need to have either
.B netscape
or 
.B lynx
executable in your path.
.SH ENVIRONMENT
.B $XEDITOR 
is used to determine the viewer of the local files.
.PP
If unset and 
.B gvim 
executable is unavailable,
.B $EDITOR 
is used to determine console editor to launch in xterm window.

.SH AUTHOR
Alexander Yukhimets
